import { atoms as a, useTheme } from "#/alf";
import { Text } from "#/components/Typography";
import { Palette } from "./Palette";

export function Theming() {
	const t = useTheme();

	return (
		<div
			style={{
				...t.atoms.bg,
				...a.gap_lg,
				...a.p_xl,
			}}
		>
			<Palette />
			<Text
				style={{
					...a.font_bold,
					...a.pt_xl,
					...a.px_md,
				}}
			>
				theme.atoms.text
			</Text>
			<div
				style={{
					...a.flex_1,
					...t.atoms.border_contrast_high,
					...a.border_t,
				}}
			/>
			<Text
				style={{
					...a.font_bold,
					...t.atoms.text_contrast_high,
					...a.px_md,
				}}
			>
				theme.atoms.text_contrast_high
			</Text>
			<div
				style={{
					...a.flex_1,
					...t.atoms.border_contrast_medium,
					...a.border_t,
				}}
			/>
			<Text
				style={{
					...a.font_bold,
					...t.atoms.text_contrast_medium,
					...a.px_md,
				}}
			>
				theme.atoms.text_contrast_medium
			</Text>
			<div
				style={{
					...a.flex_1,
					...t.atoms.border_contrast_low,
					...a.border_t,
				}}
			/>
			<Text
				style={{
					...a.font_bold,
					...t.atoms.text_contrast_low,
					...a.px_md,
				}}
			>
				theme.atoms.text_contrast_low
			</Text>
			<div
				style={{
					...a.flex_1,
					...t.atoms.border_contrast_low,
					...a.border_t,
				}}
			/>
			<div
				style={{
					...a.w_full,
					...a.gap_md,
				}}
			>
				<div
					style={{
						...t.atoms.bg,
						...a.justify_center,
						...a.p_md,
					}}
				>
					<Text>theme.atoms.bg</Text>
				</div>
				<div
					style={{
						...t.atoms.bg_contrast_25,
						...a.justify_center,
						...a.p_md,
					}}
				>
					<Text>theme.atoms.bg_contrast_25</Text>
				</div>
				<div
					style={{
						...t.atoms.bg_contrast_50,
						...a.justify_center,
						...a.p_md,
					}}
				>
					<Text>theme.atoms.bg_contrast_50</Text>
				</div>
				<div
					style={{
						...t.atoms.bg_contrast_100,
						...a.justify_center,
						...a.p_md,
					}}
				>
					<Text>theme.atoms.bg_contrast_100</Text>
				</div>
				<div
					style={{
						...t.atoms.bg_contrast_200,
						...a.justify_center,
						...a.p_md,
					}}
				>
					<Text>theme.atoms.bg_contrast_200</Text>
				</div>
				<div
					style={{
						...t.atoms.bg_contrast_300,
						...a.justify_center,
						...a.p_md,
					}}
				>
					<Text>theme.atoms.bg_contrast_300</Text>
				</div>
			</div>
		</div>
	);
}
